secrets:
  pg_user:
    environment: PG_USER
  pg_pass:
    environment: PG_PASS
  pg_host:
    environment: PG_HOST
  discord_token:
    environment: DISCORD_TOKEN
  discord_client_id:
    environment: DISCORD_CLIENT_ID

services:
  db:
    image: jonathanzhao02/snowboy:db
    restart: always
    environment:
      POSTGRES_USER_FILE: /run/secrets/pg_user
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_pass
    secrets:
      - pg_user
      - pg_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${PG_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  bot:
    image: jonathanzhao02/snowboy:bot
    restart: always
    environment:
      PG_USER_FILE: /run/secrets/pg_user
      PG_PASS_FILE: /run/secrets/pg_pass
      PG_HOST_FILE: /run/secrets/pg_host
      DISCORD_TOKEN_FILE: /run/secrets/discord_token
      DISCORD_CLIENT_ID_FILE: /run/secrets/discord_client_id
    secrets:
      - pg_pass
      - pg_user
      - pg_host
      - discord_token
      - discord_client_id
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      db:
        condition: service_healthy
  
  rest:
    image: jonathanzhao02/snowboy:rest
    restart: always
    environment:
      PG_USER_FILE: /run/secrets/pg_user
      PG_PASS_FILE: /run/secrets/pg_pass
      PG_HOST_FILE: /run/secrets/pg_host
    secrets:
      - pg_user
      - pg_pass
      - pg_host
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata: